### ISSUE TITLE
grep -U fails

### ISSUE THREAD

**Issue by dmik** [bitwiseworks/grep-os2#1]
This
```
grep -U test .
```
fails with this:
```
grep.exe: failed to set file descriptor text/binary mode: Invalid argument
```
From what I briefly see in the source (w/o debugging), it may fail  because of this check in `binary-io.c`:
```
int
__gl_setmode_check (int fd)
{
  if (isatty (fd))
    {
      errno = EINVAL;
      return -1;
    }
  else
    return 0;
}
```
when trying to set mode of a stream attached to a terminal (fairly assuming that using -U which stands for binary mode would be wrong on a terminal stream). The question is why it also fails when giving grep regular files: `isatty` should return FALSE there and `setmode` should be called as a result which should always succed on reglar files. Deeper debugging is needed.

**Comment by SilvanScherrer** [comment]
this change might help 

http://git.savannah.gnu.org/gitweb/?p=gnulib.git;a=commitdiff;h=9c383f22c6d50f4bcd7b3e3aa4611cfb61874025

**Comment by SilvanScherrer** [comment]
could you please test with the latest grep in rpm temp dir? Does this work? As the above change is applied there.

**Comment by SilvanScherrer** [comment]
https://github.com/bitwiseworks/grep-os2/commit/ec7034cf6caa3df02d114dccdb098544e1e0fb1c

**Comment by SilvanScherrer** [comment]
Please try latest grep from exp repo. If still not working reopen the issue.
